package cca.capitalcityaquatics.aquariuminfo.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val BlueDK = Color(0xFF497EB0)
val BlueLT = Color(0xFF81B2E8)
val BlueWT = Color(0xFFD8F3FF)
val Gold = Color(0xFFE19F20)
val RedDK = Color(0xFF75344E)
val Green = Color(0xFF43a047)
val BlueVar = Color(0xFF4e83b6)
val GreenVar = Color(0xFF00701a)
val RedVar = Color(0xFFa6607a)
val BlueVar2 = Color(0xFF4e83b6)
val GreenDk = Color(0xff024211)

val md_theme_light_primary = Color(0xFF00629E)
val md_theme_light_onPrimary = Color(0xFF9ACBFF)
val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D34)
val md_theme_light_secondary = Color(0xFF984064)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onSecondaryContainer = Color(0xFF3E0020)
val md_theme_light_tertiary = Color(0xFF695779)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF241532)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9ACBFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00629E)
val md_theme_light_surfaceTintColor = Color(0xFF00629E)

val md_theme_dark_primary = Color(0xFF9ACBFF)
val md_theme_dark_onPrimary = Color(0xFF003355)
val md_theme_dark_primaryContainer = Color(0xFF004A79)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_secondary = Color(0xFFFFB0CB)
val md_theme_dark_onSecondary = Color(0xFF5D1135)
val md_theme_dark_secondaryContainer = Color(0xFF7A294C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_tertiary = Color(0xFFD4BEE6)
val md_theme_dark_onTertiary = Color(0xFF392A49)
val md_theme_dark_tertiaryContainer = Color(0xFF514060)
val md_theme_dark_onTertiaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00629E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9ACBFF)
val md_theme_dark_surfaceTintColor = Color(0xFF9ACBFF)


val seed = Color(0xFF497EB0)
