package cca.capitalcityaquatics.aquariuminfo.compatibility

import cca.capitalcityaquatics.aquariuminfo.R

class MarineDataSource {
	fun loadFishCardsMarine(): List<Marine> {
		return listOf(
			//Dwarf Angel
			Marine(
				R.drawable.dwarf_angel,
				R.string.text_dwarf_angels,
				R.string.text_latin_dwarf_angels,
				R.string.list_compatible_dwarf_angels,
				R.string.list_caution_dwarf_angels,
				R.string.list_incompatible_dwarf_angels
			),
			//Large Angels
			Marine(
				R.drawable.large_angels,
				R.string.text_large_angels,
				R.string.text_latin_large_angels,
				R.string.list_compatible_large_angels,
				R.string.list_caution_large_angels,
				R.string.list_incompatible_large_angels
			),
			// Anglers / Frogs
			Marine(
				R.drawable.angler,
				R.string.text_anglers_frogs,
				R.string.text_latin_anglers_frogs,
				R.string.list_compatible_anglers_frogs,
				R.string.list_caution_anglers_frogs,
				R.string.list_incompatible_anglers_frogs
			),
			//Anthias
			Marine(
				R.drawable.anthias,
				R.string.text_anthias,
				R.string.text_latin_anthias,
				R.string.list_compatible_anthias,
				R.string.list_caution_anthias,
				R.string.list_incompatible_anthias,
			),
			//Angelfish
			Marine(
				R.drawable.angelfish,
				R.string.text_angelfish,
				R.string.text_latin_angelfish,
				R.string.list_compatible_angelfish,
				R.string.list_caution_angelfish,
				R.string.list_incompatible_angelfish
			),
			//Basslet
			Marine(
				R.drawable.baslets,
				R.string.text_basslets,
				R.string.text_latin_basslets,
				R.string.list_compatible_basslets,
				R.string.list_caution_basslets,
				R.string.list_incompatible_basslets
			),
			//Batfish
			Marine(
				R.drawable.batfish,
				R.string.text_batfish,
				R.string.text_latin_batfish,
				R.string.list_compatible_betta,
				R.string.list_caution_betta,
				R.string.list_incompatible_betta
			),
			//Blennies
			Marine(
				R.drawable.blennies,
				R.string.text_blennies,
				R.string.text_latin_blennies,
				R.string.list_compatible_blennies,
				R.string.list_caution_blennies,
				R.string.list_incompatible_blennies
			),
			//Boxfish
			Marine(
				R.drawable.boxfish,
				R.string.text_boxfish,
				R.string.text_latin_boxfish,
				R.string.list_compatible_boxfish,
				R.string.list_caution_boxfish,
				R.string.list_incompatible_boxfish
			),
			//Butterflies
			Marine(
				R.drawable.butterflies,
				R.string.text_butterflies,
				R.string.text_latin_butterflies,
				R.string.list_compatible_butterflies,
				R.string.list_caution_butterflies,
				R.string.list_incompatible_butterflies
			),
			//Cardinals
			Marine(
				R.drawable.cardinalfish,
				R.string.text_cardinals,
				R.string.text_latin_cardinals,
				R.string.list_compatible_cardinals,
				R.string.list_caution_cardinals,
				R.string.list_incompatible_cardinals
			),
			//Chromis
			Marine(
				R.drawable.chromis,
				R.string.text_chromis,
				R.string.text_latin_chromis,
				R.string.list_compatible_chromis,
				R.string.list_caution_chromis,
				R.string.list_incompatible_chromis
			),
			//Clownfish
			Marine(
				R.drawable.clownfish,
				R.string.text_clownfish,
				R.string.text_latin_clownfish,
				R.string.list_compatible_clownfish,
				R.string.list_caution_clownfish,
				R.string.list_incompatible_clownfish
			),
			//Hatchets
			Marine(
				R.drawable.hatchets,
				R.string.text_hatchets,
				R.string.text_latin_hatchet,
				R.string.list_compatible_hatchets,
				R.string.list_caution_hatchets,
				R.string.list_incompatible_hatchets
			),
			//Killifish
			Marine(
				R.drawable.killifish,
				R.string.text_killifish,
				R.string.text_latin_killifish,
				R.string.list_compatible_killifish,
				R.string.list_caution_killifish,
				R.string.list_incompatible_killifish
			),
			//Larger Catfish
			Marine(
				R.drawable.large_catfish,
				R.string.text_catfish,
				R.string.text_latin_larger_catfish,
				R.string.list_compatible_catfish,
				R.string.list_caution_catfish,
				R.string.list_incompatible_catfish
			),
			//Loach
			Marine(
				R.drawable.loaches,
				R.string.text_loach,
				R.string.text_latin_loach,
				R.string.list_compatible_loach,
				R.string.list_caution_loach,
				R.string.list_incompatible_loach
			),
			//Molly
			Marine(
				R.drawable.molly,
				R.string.text_molly,
				R.string.text_latin_molly,
				R.string.list_compatible_molly,
				R.string.list_caution_molly,
				R.string.list_incompatible_molly
			),
			//Platy
			Marine(
				R.drawable.platy,
				R.string.text_platy,
				R.string.text_latin_platy,
				R.string.list_compatible_platy,
				R.string.list_caution_platy,
				R.string.list_incompatible_platy
			),
			//Pleco
			Marine(
				R.drawable.pleco,
				R.string.text_pleco,
				R.string.text_pleco_latin,
				R.string.list_compatible_pleco,
				R.string.list_caution_pleco,
				R.string.list_incompatible_pleco
			),
			//Rainbowfish
			Marine(
				R.drawable.rainbowfish,
				R.string.text_rainbowfish,
				R.string.text_latin_rainbowfish,
				R.string.list_compatible_rainbowfish,
				R.string.list_caution_rainbowfish,
				R.string.list_incompatible_rainbowfish
			),
			//Rasboras
			Marine(
				R.drawable.rasbora,
				R.string.text_rasboras,
				R.string.text_latin_rasbora,
				R.string.list_compatible_rasboras,
				R.string.list_caution_rasboras,
				R.string.list_incompatible_rasboras
			),
			//Sharks
			Marine(
				R.drawable.freshwater_shark,
				R.string.text_shark,
				R.string.text_latin_shark,
				R.string.list_compatible_shark,
				R.string.list_caution_shark,
				R.string.list_incompatible_shark
			),
			//Suckermouth Catfish
			Marine(
				R.drawable.suckermouth_catfish,
				R.string.text_sucker_catfish,
				R.string.text_latin_larger_catfish,
				R.string.list_compatible_suckermouth_catfish,
				R.string.list_caution_suckermouth_catfish,
				R.string.list_incompatible_suckermouth_catfish
			),
			//Swordtails
			Marine(
				R.drawable.swordtail,
				R.string.text_swordtail,
				R.string.text_latin_swordtail,
				R.string.list_compatible_swordtail,
				R.string.list_caution_swordtail,
				R.string.list_incompatible_swordtail
			),
			//Tetras
			Marine(
				R.drawable.tetra,
				R.string.text_tetra,
				R.string.text_latin_tetra,
				R.string.list_compatible_tetra,
				R.string.list_compatible_tetra,
				R.string.list_incompatible_tetra
			),
			//Misc. Fish
			Marine(
				R.drawable.misc_fish,
				R.string.text_misc_fish,
				R.string.text_latin_various,
				R.string.list_compatible_misc,
				R.string.list_caution_misc,
				R.string.list_incompatible_misc
			),
			//Invertebrates
			Marine(
				R.drawable.shrimp,
				R.string.text_inverts,
				R.string.text_latin_various,
				R.string.list_compatible_inverts,
				R.string.list_caution_inverts,
				R.string.list_incompatible_inverts
			),
			//Brackish Fish
			Marine(
				R.drawable.brackish,
				R.string.text_brackish,
				R.string.text_latin_various,
				R.string.list_compatible_brackish,
				R.string.list_caution_brackish,
				R.string.list_incompatible_brackish
			),
			//Pond Fish
			Marine(
				R.drawable.koi,
				R.string.text_pond,
				R.string.text_latin_various,
				R.string.list_compatible_pond,
				R.string.list_compatible_pond,
				R.string.list_incompatible_pond
			),
			//Marine Plants
			Marine(
				R.drawable.java_fern,
				R.string.text_platy,
				R.string.text_latin_various,
				R.string.list_compatible_platy,
				R.string.text_fancy_goldfish,
				R.string.text_pond
			),
		)
	}
}